# Generated by Django 2.2.24 on 2021-12-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('read_write_serializer_demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readwritefielddemomodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
